runtime:       go
api_version:   go1

handlers:

- url:         /static/css
  static_dir:  static/css

- url:         /static/images
  static_dir:  static/images


# All active conten handled by the app
- url:         /admin/.*
  script:      _go_app
  login:       admin

- url:         /.*
  script:      _go_app
