runtime:       go111

handlers:

- url:         /static/css
  static_dir:  static/css

- url:         /static/images
  static_dir:  static/images


# All active conten handled by the app
# - url:       /admin/.*
#   script:    _go_app

- url:         /.*
  script:      auto
  secure:      always
