runtime: go
api_version: go1

handlers:
# If the path is empty, show static index.html file
# - url: /
#   static_files: index.html
#   upload: index.html

# Otherwise, find file in static directory
- url: /static/img
  static_dir: static/img

- url: /static/css
  static_dir: static/css

- url: /static
  static_dir: static

# All URLs are handled by the Go application script
- url: /.*
  script: _go_app
